# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build, upload artifact and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  job_build:
    name: Build, test and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.21'

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Move build binary to bin/
        run: |
            mkdir -p bin/
            mv gocheckip bin/
        
      - name: Upload binary to artifacts
        uses: actions/upload-artifact@v4
        with:
            name: gocheckip
            path: bin/gocheckip

  job_release:
    permissions:
      contents: write
    needs: job_build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check REF NAME
      run: echo "Got ref name $GITHUB_REF_NAME"

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: gocheckip
        path: bin/
    - name: Create a GH release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/gocheckip
